# Manual agent loop — repeatedly calls the Responses API,
# executes requested tools, and feeds tool outputs back into the loop
# until the model produces a final answer.

import json
from openai import OpenAI

from app.config import CHAT_MODEL, MAX_ITERATIONS
from app.tools.registry import TOOL_SCHEMAS, TOOL_REGISTRY
from app.retrieval.query_type import is_numeric_query

_client: OpenAI | None = None


def _get_client() -> OpenAI:
    global _client
    if _client is None:
        _client = OpenAI()
    return _client


SYSTEM_PROMPT = """You are an aviation technical assistant grounded strictly in the Boeing 737 flight manual.

You have access to three tools:
- search_documentation: search the manual for policies, procedures, and performance data
- get_current_datetime: get the current UTC date and time
- get_weather: get current weather conditions (temperature, wind, visibility, humidity) for any city

Rules:
- Always call search_documentation for any question that may be covered in the manual.
- Answer ONLY using information returned by the tools. Do not use your own training knowledge to fill gaps.
- If the retrieved content does not contain a clear answer, you MUST say: "I could not find this information in the provided manual." Do NOT infer, guess, or supplement with outside knowledge.
- Be concise and professional. Write in an aviation-style tone suitable for flight crew. Do not add unrequested context or background explanations.
- Always cite the page numbers from the search results.
- Do not modify or interpret numeric values — report them exactly as they appear in the manual.
- When search_documentation returns a single numeric value or "NOT FOUND", report it verbatim with the page citation. The format VALUE (UNIT) means VALUE is the answer — e.g. "52.2 (1000 KG)" means 52.2 thousand kg. Do NOT report only the unit. Do NOT recompute, rephrase, or add explanation.
- When calling search_documentation, pass ALL specific conditions from the user's question exactly as stated — preserve every number, temperature, altitude, weight, and unit verbatim. Do NOT paraphrase, shorten, or remove any values.

Time and date rules:
- When asked about the current time or date, always call get_current_datetime first.
- Always state the UTC time from the tool result.
- If the user asks about a specific city or timezone, also derive and state the local time for that city using your knowledge of standard UTC offsets (e.g. Tokyo = UTC+9, London = UTC+0/+1 DST, New York = UTC-5/-4 DST). Always mention both UTC and local time.
- Always include the day of week and full date in the answer, not just the time."""


def run(query: str) -> dict:
    """
    Runs the full agent loop for a single user query.
    The model decides:
    - which tools to call
    - in what order
    - when enough information has been gathered

    Returns:
        {
            "answer": str,
            "references": [{"document_title": str, "pages": [int, ...]}],
            "tool_calls": [{"tool": str, "arguments": dict}]
        }
    
    """
    client = _get_client()

    # Start the conversation with system instructions and the user query:
    input_items = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": query},
    ]


    tool_call_trace: list[dict] = []       # ordered log of every tool invoked
    
    # References only come from search_documentation results:
    all_chunks: list[dict] = []            # raw chunks from search_documentation calls
    answer = ""
    iteration = 0

    # Main loop: keep calling the model until we have an answer or hit the max iterations:
    while iteration < MAX_ITERATIONS:
        response = client.responses.create( 
            model=CHAT_MODEL,
            input=input_items,
            tools=TOOL_SCHEMAS,
        )

        # Extract all tool calls generated by the model:
        function_calls = [
            item for item in response.output
            if item.type == "function_call"
        ]

        # If no tool calls exist, the model has finished reasoning:
        if not function_calls: 

            # Extract the final answer from the model's response:
            for item in response.output:
                if item.type == "message":
                    for block in item.content:
                        if block.type == "output_text":
                            answer = block.text
                            break
            break

        # API expects a flat list, not nested arrays, 
        # So append all response items directly into input_items.
        input_items.extend(response.output)

        # Execute each tool call and append results:
        tool_outputs = []
        for fc in function_calls:
            tool_name = fc.name
            arguments = json.loads(fc.arguments) if fc.arguments else {}

            # Logging to trace tool call history
            tool_call_trace.append({"tool": tool_name, "arguments": arguments})

            try:
                fn = TOOL_REGISTRY[tool_name]

                # For numeric/table-based queries, always pass the original
                # user query because the model may paraphrase tool arguments
                # and accidentally remove important numbers or units.
                effective_args = arguments
                if tool_name == "search_documentation" and is_numeric_query(query):
                    effective_args = {"query": query}
                result = fn(**effective_args)

                # search_documentation returns:
                # - formatted text
                # - retrieved chunks for references

                if tool_name == "search_documentation":
                    output_text, chunks = result
                    all_chunks.extend(chunks)
                else:
                    output_text = str(result)

            except Exception as e:
                output_text = f"ERROR: {e}" # Error handling for tool execution failures
            
            # Feed tool result back into the next iteration:
            tool_outputs.append({
                "type": "function_call_output",
                "call_id": fc.call_id,
                "output": output_text,
            })

        input_items.extend(tool_outputs)
        iteration += 1

    else:
        # Fallback if the loop exceeds the safety limit:
        answer = (
            "I was unable to produce a complete answer within the allowed number of steps. "
            "Please try rephrasing your question."
        )

    references = _build_references(all_chunks)
    return {"answer": answer, "references": references, "tool_calls": tool_call_trace}


def _build_references(chunks: list[dict]) -> list[dict]:
    """
    Groups retrieved pages by document title
    and removes duplicate page numbers.
    """
    
    grouped: dict[str, set[int]] = {}
    for chunk in chunks:
        title = chunk["document_title"]
        page = chunk["page"]
        grouped.setdefault(title, set()).add(page)

    return [
        {"document_title": title, "pages": sorted(pages)}
        for title, pages in grouped.items()
    ]
